### ISSUE TITLE
Make handling of single-end vs paired-end seq friendlier

### ISSUE THREAD

**Issue by oneillkza** [oneillkza/ContiBAIT#13]
Right now, when stgrandSeqFreqTable is called, if the wrong type of data is specified, the call to Rsamtools returns no reads, which can cause downstream (and potentially quite cryptic) errors.

We should:

1) Make it clear in the documentation that the type of data absolutely needs to be specified
2) Try to handle the error better.
3) Ideally, detect whether the data is single or paired end ourselves so we don't need to worry about this.

**Comment by rareaquaticbadger** [comment]
See latest pull request.

strandSeqFreqTable prints warning and breaks if pairedEnd is incorrectly set. runContiBAIT now has parameters listed to terminal when run.  I think this should be sufficient unless there's a clever way to initially assess whether data is PE or SE automatically, which as far as I'm aware, there isn't.

**Comment by oneillkza** [comment]
Awesome! Solution in this pull request: https://github.com/oneillkza/ContiBAIT/pull/10
