### ISSUE TITLE
Fix or Remove StrandStateMatrix 

### ISSUE THREAD

**Issue by mgottl04** [oneillkza/ContiBAIT#2]
preprocessStrandTable returns a StrandStateMatrix that does not pass the validity check. Either needs to be removed or updated.
## Line 34

<pre><code>

animal.strands <- preprocessStrandTable(animal.tab[[1]], 
                                        lowQualThreshold=0, 
                                        minLib=6,
                                        )

</code></pre>

Gives

<pre><code>
Error in validObject(.Object) : 
  invalid class “StrandStateMatrix” object: FALSE 
</code></pre>

**Comment by oneillkza** [comment]
Resolved with the following commit:

https://github.com/oneillkza/ContiBAIT/commit/2be17ee3dc3bbf81a62afcf0db70c06eb749880a
